### ISSUE TITLE
Wrong dates displayed, possibly time zone issue?

### ISSUE THREAD

**Issue by cperciva** [scraly/developers-conferences-agenda#1254]
I just added BSDCan as June 11-14 2025, but when I load https://developers.events/#/2025/list I see:
`10-Jun 13-Jun BSDCan 2025 [www.bsdcan.org](https://www.bsdcan.org/2025/) Ottawa, ON (Canada)`

It looks like https://developers.events/all-events.json has starting and ending timestamps at 00:00 UTC on the 11th and 14th respectively; I don't think the exact time of day is used or displayed anywhere on this site, but since I'm in Canada I'm wondering if those timestamps are getting converted to my local timezone and thus ending up with the wrong dates.

**Comment by tedyoung** [comment]
I noticed this as well. Times should **not** be translated if it's an in-person conference. If I'm in the USA and looking at European conferences, I should see the dates in terms of their local date (time) and not translated to my time zone.

**Comment by scraly** [comment]
Hi,
In the #1113 PR a fixed have been made for this bug also.
Dates are pushed in UTC time in the calendar grid.
is it better now?

**Comment by cperciva** [comment]
Also I think you meant #1319 not #1113.

**Comment by scraly** [comment]
Yes it was in #1319  :)

**Comment by scraly** [comment]
The bug is fixed?

**Comment by cperciva** [comment]
No, looks like it's still broken for browsers in which are behind UTC.  Every event is showing up on the calendar as being the day before it actually starts.

**Comment by scraly** [comment]
In the calendar grid, the dates was created in UTC.
It should be fixed now 🤞.

**Comment by tedyoung** [comment]
I'm still seeing wrong dates, e.g., DDD Europe shows as June 7-11, which is one day off. If I click th edit button, the form shows the correct dates. See the image.

![image](https://github.com/user-attachments/assets/8abdff6d-d569-424e-9abe-2523ea597bfc)

**Comment by cperciva** [comment]
Confirmed, still broken for me.  I think there's one or more getDate calls which should be getUTCDate?

**Comment by scraly** [comment]
Thanks for the tests.

on my side the events are corrected displayed:

<img width="337" height="297" alt="Image" src="https://github.com/user-attachments/assets/66ff3d42-64bd-4188-8183-5146b5a48244" />

<img width="1404" height="109" alt="Image" src="https://github.com/user-attachments/assets/b85be5f7-0d14-4a4b-ac5b-46e862a15c88" />

<img width="745" height="446" alt="Image" src="https://github.com/user-attachments/assets/0b094e8d-9125-4bd7-93d5-1d0d1522e9df" />

So I'll continue to try to fix it :) .

**Comment by cperciva** [comment]
> on my side the events are corrected displayed:

GitHub says you're in Toulouse, which probably explains that -- can you try switching your time zone (probably in your desktop environment, I'm guessing the browser will inherit that) to something from North America?

**Comment by scraly** [comment]
I confirm the cause: the event dates were stored at midnight UTC. But the UI was reading them with local-time date methods. In timezones behind UTC, especially in North America (tested with Montreal TZ), that could shift events to the previous day and cause multi-day events to disappear from the first day.

**Comment by scraly** [comment]
Tested with Montreal TZ and it seems OK.

@cperciva & @tedyoung is it OK now on your sides? 🤞

**Comment by cperciva** [comment]
Looks good to me now, thanks!

**Comment by tedyoung** [comment]
@scraly Yes, looks good here in San Francisco, CA, USA!

**Comment by scraly** [comment]
That's a good news! ❤️
